repos:
  - repo: local
    hooks:
      - id: django-tests
        name: Run Django Tests
        language: system
        stages: [pre-commit]
        # entry: bash -c "cd aetheranime && python manage.py test"
        entry: powershell -c "cd aetheranime; python manage.py test"
