# Generated by Django 5.1.4 on 2024-12-16 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comments", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="animestatus",
            name="status",
            field=models.CharField(
                choices=[
                    ("watched", "Просмотрено"),
                    ("planned", "В планах"),
                    ("watching", "Смотрю"),
                    ("paused", "Отложено"),
                    ("dropped", "Брошено"),
                ],
                max_length=10,
            ),
        ),
    ]
