# Generated by Django 5.1.4 on 2025-01-10 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comments", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="content",
            field=models.TextField(blank=True, null=True),
        ),
    ]
