# Generated by Django 5.1.4 on 2024-12-21 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_auth", "0002_alter_customuser_email_comment_history_review_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="is_verified",
            field=models.BooleanField(default=False, verbose_name="Verified User"),
        ),
    ]
