# Generated by Django 5.1.4 on 2025-01-03 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_auth", "0003_customuser_is_verified"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="tag",
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
