# Generated by Django 5.1.4 on 2024-12-15 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("animes", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="genre",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
