# Generated by Django 5.1.4 on 2025-01-10 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("animes", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="animepreview",
            old_name="poster_url",
            new_name="originalUrl",
        ),
    ]
