# Generated by Django 5.1.4 on 2024-12-15 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("animes", "0002_alter_genre_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="genre",
            name="id",
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
    ]
