# Generated by Django 5.1.4 on 2024-12-16 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("animes", "0003_alter_genre_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="anime",
            name="aired_date",
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="anime",
            name="release_date",
            field=models.DateField(null=True),
        ),
    ]
