# Generated by Django 5.1.4 on 2024-12-16 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("animes", "0004_anime_aired_date_alter_anime_release_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="anime",
            name="aired_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="anime",
            name="release_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
