# Generated by Django 5.1.4 on 2025-01-21 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_alter_customuser_username"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="customuser",
            managers=[],
        ),
    ]
